### ISSUE TITLE
Error: unable to determine if image already exists for image "docker://dvcorg/cml-py3:latest": Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by ucalyptus** [iterative/cml_base_case#5]
Trying to use [Act](https://github.com/nektos/act) that allows u to locally run ur actions. Got this error on colab when trying !act
# Link to reproduce this 
https://colab.research.google.com/gist/ucalyptus/4d3e21374cd50a48f9aa898925fb03ff/trial-bedardi-raja.ipynb

cc @elleobrien

**Comment by ucalyptus** [comment]
# Tried to local system as well
![](https://user-images.githubusercontent.com/36279638/90505297-fe29e780-e16f-11ea-9bbe-1c8a0a23ae58.png)

**Comment by elleobrien** [comment]
Hi @ucalyptus, this seems like a permissions error on your local workspace. I suspect it's outside the scope of CML and will happen with any Docker container you try to use- [see this issue on the Act repo](https://github.com/nektos/act/issues/75)

Note that you can use `npm` to install the CML functions instead of pulling the Docker image
```
npm i -g @dvcorg/cml
```

**Comment by ucalyptus** [comment]
@elleobrien so I can replace `container: docker://dvcorg/cml-py3:latest` with `npm i -g @dvcorg/cml` ? 
Sorry for the noob question, I am new to yml configs.

**Comment by elleobrien** [comment]
No worries! I'm not 100% positive it will work for you, because I've never tried using Act. But you would try deleting the line`container: docker://dvcorg/cml-py3:latest`, and in the `run` field add `npm i -g @dvcorg/cml`.

**Comment by elleobrien** [comment]
Like so:
```
name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i -g @dvcorg/cml
```
